dirksimple_cliff_allow_buy_in = "true"
dirksimple_cliff_god_mode = "false"
dirksimple_cliff_infinite_lives = "true"
dirksimple_cliff_show_full_hints = "true"
dirksimple_cliff_show_hanging_scene = "false"
dirksimple_cliff_show_hints = "true"
dirksimple_cliff_show_lives_and_score = "true"
dirksimple_cliff_show_should_have_hint = "2"
dirksimple_cliff_starting_lives = "6"
